num1=float(input("1-sonni kiriting:"))
num2=float(input("2-sonni kiriting:"))
num3=float(input("3-sonni kiriting:"))
largest=max(num1, num2, num3)
smallest=min(num1, num2, num3)
print("Eng katta son",largest)
print("Eng kichik son",smallest)