sentence=input("Biror matn kiriting")
old_world=input("qaysi so'zni almashtirmoqchisiz?")
new_world=input("yangi so'zni kiriting:")
updated_sentence=sentence.replace(old_world, new_world)
print("yangi gap:", updated_sentence)
